### PR TITLE
Fix package

### PR DESCRIPTION
**Pull request by syohex**

### CODE REVIEW

**Comment by jeffgran** [comment]
Thank you for helping cleanup. I will merge this, except that the "malformed let" I think is not malformed. The last line is supposed to be calling the function below, not a variable assignment.

**Comment by syohex** [comment]
original `elscreen-bg-get-current-property` is here.

``` el
(defun elscreen-bg-get-current-property (name)
  (let ((properties (elscreen-get-screen-property (elscreen-get-current-screen)))
        (elscreen-bg-get-alist name properties))
    ))
```

Body of `let` is nothing. And `properties` of argument of `elscreen-bg-get-alist` is `nil`.
Because here is `let`, not `let*`.

**Comment by jeffgran** [comment]
Aha! you're right. Also, notice that this function is never called anywhere else in the code. We should just remove it altogether.

**Comment by jeffgran** [comment]
I believe I have fixed all these problems in the latest commits, so I'm closing the pull request. Please let me know if you disagree.

**Pull request closed without merging**
